PB-22 ContactService
tel-ran-de/phonebook-16-19-2 pull request #14
Opened 2021-09-10 07:56 UTC by VolvachevaNatalya

2021-09-10 08:54 UTC, AR1988 requested changes

2021-09-10 08:54 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/exception/ContactException.java
> +public class ContactException extends RuntimeException{
Contact**Not**Exception

2021-09-10 08:54 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/ContactService.java
> +    public void remove (Long id) {
ctrl+alt+l
ctrl+alt+o

2021-09-10 08:54 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/ContactService.java
> +    public Contact add(Contact contact) {
add(String fName, String lName, ...)

2021-09-10 08:54 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/ContactService.java
> +    }
написать метод edit и протестировать

2021-09-10 08:54 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/service/ContactServiceTest.java
> +        Assertions.assertThrows(ContactException.class, () -> {
вытащить ошибку и сравнить текст ошибки с ожидаемым

2021-09-10 09:24 UTC, AR1988 requested changes

2021-09-10 09:24 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/service/ContactServiceTest.java
> +    }
https://github.com/AR1988/telran_16/blob/main/21_08_30_heroes_api/src/test/java/com/example/backrorheroes/service/HeroServiceTest.java

2021-09-10 09:24 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/ContactService.java
> +    public void remove (Long id) {
сделай проверку, если контакт по id есть в бд, то удаляй, если нет то выкидывай ошибку **ContactNotException**

2021-09-10 13:10 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/exception/ContactException.java
> +public class ContactException extends RuntimeException{
@AR1988  Not or Null ??

2021-09-10 13:33 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/exception/ContactException.java
> +public class ContactException extends RuntimeException{
ContactNotFoundException

2021-09-11 05:50 UTC, AR1988 requested changes

2021-09-11 05:50 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/service/ContactServiceTest.java
> +                        && argument.getGroup() == Group.FAMILY));
Редактирование контакта, проверить кейс, если контакт не найден

2021-09-14 06:32 UTC, AR1988 approved these changes

2021-09-14 06:32 UTC, merged