Pb-28-2 Email REST Controller
tel-ran-de/phonebook-16-19-2 pull request #22
Opened 2021-09-16 18:52 UTC by VolvachevaNatalya

2021-09-16 20:32 UTC, AR1988 requested changes
Работы проделала много 👍👍👍. Очень много 👍👍👍👍👍👍👍👍.
Сделано больше чем нужно  было
По сути тут **три** карточки
- обработчик ошибок
- контролер с дто
- валидации полей дто

Создай эти карточки в трелло и присоеденись к ним. Потом перемести в **Code Review** колонку.
👌

_В следующий раз выполняй задачу  которая описана в карточке😳. Ты немного вылезла за рамки задачи._

А так же внеси необходимые изменения😁

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +@Data
- Что даёт @Data?
- нужно ли нам тут все то, что даёт @Data?

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +    @NotEmpty @Email
Мы договаривались сделать проверку в отдельном тикете. Но раз уже работа сделана, тогда оставим тут. Создай тикет и присоеденись к нему. Перетащи тикет в Code Review.

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/EmailService.java
> +    public Email edit(Long id, String email, boolean isFavorite) {
Пускай редактирование ни чего не возвращает.
Мы и так знаем что мы редактируем и какие изменения будут применены при редактировании

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/EmailService.java
> +    public void checkIfEmailDoesNotExist(String email) {
Данный метод нам не нужен. Мы должны иметь возможность сохранять одинаковые адреса электронной почты. Удали пожалуйста и удали все что с этим методом связанно

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/EmailService.java
> +import org.springframework.stereotype.Service;
Не вижу где используется этот импорт. Он необходим?

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +    @NotEmpty @Email
Для валидации Email лучше использовать @pattern.

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/ExceptionHandlerController.java
> +    }
Добавь обработчик ошибок валидации полей.

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/mapper/EmailMapper.java
> +     public static CreateEmailResponse emailToRegisterEmailResponse(Email email) {
Сделай методы nö-static. И повешай аннотацию классу @Component. Что бы потом внедрить в сервис.

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/EmailController.java
> +import static com.telran.phonebookapi.mapper.EmailMapper.emailToFullEmailResponse;
Не стачиный мапер, пожалуйста 👌

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/EmailController.java
> +        this.emailService = emailService;
Внедри мапер через конструктор

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/EmailController.java
> +        emailService.checkIfEmailDoesNotExist(createEmailRequest.getEmail());
Проверка не нужна. Пользователь может сохранять одинаковые емаилы

2021-09-16 20:32 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/exception/EmailExistsException.java
> +public class EmailExistsException extends RuntimeException {
Del

2021-09-17 05:29 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +@Data
@DaTa дает еам геттеры, сеттеры, и конструктор

2021-09-17 05:34 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +    @NotEmpty @Email
@AR1988 Я видимо пропустила этот момент, когда договаривались про отдельный тикет... мне показалось, валидация идет в одном пакете с контроллером/
Сделала тикет Pb-29-1 Email validation, перетащила в Code Review

2021-09-17 05:46 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/EmailService.java
> +    public void checkIfEmailDoesNotExist(String email) {
@AR1988  Удалила

2021-09-17 05:47 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/EmailService.java
> +import org.springframework.stereotype.Service;
Нужен для аннотации @Service

2021-09-17 05:58 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +    @NotEmpty @Email
Почему и чем это лучше?
Какой именно паттерн надо использовать?

2021-09-17 06:02 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/EmailService.java
> +    public Email edit(Long id, String email, boolean isFavorite) {
Обьясни пожалуйста почему это принципиально.
Код рабочий, ошибок нет
Недостаточно поменять Email на void, это требует дополнительных измненений какихто...

2021-09-17 06:04 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/mapper/EmailMapper.java
> +     public static CreateEmailResponse emailToRegisterEmailResponse(Email email) {
Done

2021-09-17 06:04 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/EmailController.java
> +import static com.telran.phonebookapi.mapper.EmailMapper.emailToFullEmailResponse;
Done

2021-09-17 06:04 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/EmailController.java
> +        this.emailService = emailService;
Done

2021-09-17 06:04 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/EmailController.java
> +        emailService.checkIfEmailDoesNotExist(createEmailRequest.getEmail());
Done

2021-09-17 06:06 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/exception/EmailExistsException.java
> +public class EmailExistsException extends RuntimeException {
?

2021-09-17 06:32 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/ExceptionHandlerController.java
> +    }
Подскажи пожалуйста каким образом, не очень поняла

2021-09-17 06:34 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +@Data
А так же equals, hashcode и toString. Из всех этих методов нам нужен конструктор и гетеры.

2021-09-17 06:36 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/service/EmailService.java
> +    public Email edit(Long id, String email, boolean isFavorite) {
Когда мы отправляем запрос на редактирование, мы знаем все что нам нужно знать. Т.е. нам достаточно получить 2хх код, чтобы применить изменения.

2021-09-17 06:37 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +@Data
В смысле мне нужно убрать дата, и добавить конструктор и геттеры?

2021-09-17 06:41 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/EmailController.java
> +        emailService.checkIfEmailDoesNotExist(createEmailRequest.getEmail());
У нас будет другая сущность User, у которого будет уникальный email в качестве поля класса в роле id.

А этот Email это одльная сущность, которая может повторяться. У контактов может быть много разных и одинаковых Email.

2021-09-17 06:42 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/exception/EmailExistsException.java
> +public class EmailExistsException extends RuntimeException {
Разве не эта ошибка пробрасывается, если выполнять проверку на уникальность emal в сервисе?

2021-09-17 06:48 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/exception/EmailExistsException.java
> +public class EmailExistsException extends RuntimeException {
Got it
Removed

2021-09-17 13:12 UTC, AR1988 requested changes

2021-09-17 13:12 UTC, AR1988 commented on phonebook-ui/src/app/model/contact.ts
> -}
это что за изменения?

2021-09-17 13:41 UTC, AR1988 requested changes

2021-09-17 13:41 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/dto/CreateEmailRequest.java
> +    private boolean isFavorite;
так же добавь валидацию

2021-09-17 14:44 UTC, VolvachevaNatalya commented on phonebook-ui/src/app/model/contact.ts
> -}
@AR1988  Похоже, что просто пустая строка, или добавилась или удалилась. Я понимаю, что этого тут быть не должно, но не знаю как поправить

2021-09-17 17:00 UTC, AR1988 approved these changes

2021-09-17 17:02 UTC, merged