Pb 33,39
tel-ran-de/phonebook-16-19-2 pull request #30
Opened 2021-09-23 18:26 UTC by Juergen-J

Added phone-add form,phone-details, phone service(update, delete, add, get)

2021-09-23 19:59 UTC, AR1988 requested changes

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.ts
> +  flag: boolean | undefined;
что за флаг?

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.ts
> +  ngOnDestroy(): void {
сделай его последним метом

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone.component.ts
> +  ngOnDestroy(): void {
сделай последним метом

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.ts
> +      favorite: new FormControl(this.flag),
favorite: new FormControl(**this.flag**) ->  favorite: new FormControl(**this.phone?.isFavorite**)
???

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/add-phone-form/add-phone-form.component.html
> +    <img (click)="clear()" class="delete-line" src="assets/images/delete.png"
class * 2
class="delete-line"
class="pointer"

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone.component.ts
> +  addPhoneForm: boolean = false;
слишком много флагов....

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.html
> +  <form [formGroup]="updatePhoneForm" class="row">
`<form [formGroup]="updatePhoneForm" class="row" (ngSubmit)="onClickSave()">`

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.ts
> +    if (this.phone == this.updatePhoneForm.value) {
**if (this.phone === this.updatePhoneForm.value) {**

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.ts
> +      countryCode: new FormControl(this.phone?.countryCode, Validators.required),
нужно так же передать в форму id телефона. Отображать не надо, просто записать

```
    this.updatePhoneForm = new FormGroup({
      countryCode: new FormControl(this.phone?.countryCode, Validators.required),
      telephoneNumber: new FormControl(this.phone?.telephoneNumber, Validators.required),
      favorite: new FormControl(this.flag),
      contactId: new FormControl(this.contactId),
      id: new FormControl(this.phone?.id)
    });
```

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/service/phone.service.ts
> +    return this.httpClient.put(url,phone,this.httpOptions);
put<void>

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/service/phone.service.ts
> +  updatePhone( phone:Phone):Observable<any>{
<void>

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.ts
> +  toggleStar() {
нужно убрать. Значение звездочки не должно переключаться по нажатию, а должно завесить от значения phone.isFavorite

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.ts
> +    const addSubscription = this.phoneService.deletePhone(phone.id).subscribe();
если ошибка

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.html
> +             [ngClass]="flag ? 'star-true': 'star-false'"
[ngClass]="contact.isFavorite ? 'star-true': 'star-false'"

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.html
> +        <div (click)="toggleStar()"
зачем это тут?

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/add-phone-form/add-phone-form.component.ts
> +  flag!: boolean;
зачем?

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/add-phone-form/add-phone-form.component.ts
> +      .subscribe(value => this.router.navigate(['contacts', this.contactId]), error => this.logError = error);
зачем перенаправлять пользователя обратно на ту же страницу?
для обновления данных, можно использовать EentEmitter и отправить родительскому компоненте добавленный элемент(phone) в массив phones в родительском компоненте

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/add-phone-form/add-phone-form.component.ts
> +  toggleStar() {
зачем?

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/add-phone-form/add-phone-form.component.html
> +    <div class="">
class = ""

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/add-phone-form/add-phone-form.component.html
> +      <div (click)="toggleStar()"
(click)="toggleStar()" ???

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/add-phone-form/add-phone-form.component.html
> +           [ngClass]="flag ? 'star-true': 'star-false'"
[ngClass]="contact.isVaforite ? 'star-true': 'star-false'"

2021-09-23 19:59 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone-element/phone-element.component.ts
> +      .subscribe(value => this.router.navigate(['contacts', 1]), error => this.logError = error);
тоже самое что и при добавлении, не нужно перенаправлять...

2021-09-26 20:55 UTC, Juergen-J commented
возникает две проблемы:
1) когда мы добавили телефон, то при попытке его изменить мы получим ошибку - не имеет ИД
2) при изменении ИЗБРАННОЕ - не сохраняются изменения 
!НУЖНО ТЕСТИРОВАТЬ С СЕРВЕРОМ

2021-09-27 10:14 UTC, AR1988 requested changes
Обнови до текущего майн, и настрой корректную работу с backend

2021-09-27 10:14 UTC, AR1988 commented on phonebook-ui/src/app/add-phone-form/add-phone-form.component.ts
> +        this.addPhone.emit(this.phoneForm.value);
Если я правильно помню, при добавлении нам сервер возвещает добавленный объект. У которого будет так же уже установленное id.

his.phoneForm.value - id равно 0

2021-09-27 10:14 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone.component.ts
> +  sortPhones(): void {
посмотри сортировку используя pipe 
https://stackoverflow.com/questions/35158817/orderby-pipe-issue

рассмотри у @Pipe параметр **pure**

2021-09-27 10:14 UTC, AR1988 commented on phonebook-ui/src/app/contact-details/phone/phone.component.ts
> +    this.phones.forEach(value => {
еще можно найти индекс обновляемого телефона. У массивов есть встроенный метод. И по индексу заменить элемент. `this.phones[elementIndex] = $event.`
но и твое решение тоже верное
Попробуй оба и выбери то которое тебе более понятно

2021-09-28 10:41 UTC, AR1988 approved these changes

2021-09-28 10:41 UTC, merged