Pb 11
tel-ran-de/phonebook-16-19-2 pull request #6
Opened 2021-09-05 13:20 UTC by Juergen-J

2021-09-06 09:21 UTC, AR1988 requested changes

2021-09-06 09:21 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    @Enumerated(EnumType.STRING)
`@ElementCollection` or  `@Enumerated`
выяснить разницу и что лучше использовать

2021-09-06 09:21 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    @Setter(AccessLevel.PRIVATE)
убрать сеттер, проверить есть ли геттер для id

2021-09-06 09:21 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    @OneToMany
`@OneToMany(mappedBy= "", cascade = CascadeType.REMOVE)`

2021-09-06 09:39 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +
создать методы для добавления в список телефона, адреса, почты

addPhone(Phone)....

2021-09-06 18:25 UTC, Juergen-J commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    @Enumerated(EnumType.STRING)
I chose @Enumerated

2021-09-06 18:25 UTC, Juergen-J commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    @Setter(AccessLevel.PRIVATE)
Ready

2021-09-06 18:26 UTC, Juergen-J commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    @OneToMany
ready

2021-09-06 18:26 UTC, Juergen-J commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +
ready

2021-09-06 19:34 UTC, AR1988 requested changes

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/repository/ContactRepository.java
> +public interface ContactRepository extends JpaRepository<Contact, Integer> {
не входит в задачу тикета

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/entity/AddressTest.java
> +public class AddressTest {
пустой класс?

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/entity/EmailTest.java
> +public class EmailTest {
пустой класс?

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/entity/PhoneTest.java
> +    @InjectMocks
моки тут не нужны

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/entity/ContactTest.java
> +    private static Group group;
зачем тут статичная переменная Group group

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/entity/ContactTest.java
> +    Contact contact;
зачем?

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Email.java
> +    public Email(@NonNull String email,boolean isFavorite, @NonNull Contact contact) {
пробелы между ","

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    // TODO: 06.09.2021
комментарий нужно удалить

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Address.java
> +
лишний перенос строки

2021-09-06 19:34 UTC, AR1988 commented on phonebook-api/build.gradle
implementation 'com.h2database:h2'
не включена h2 db

2021-09-06 20:12 UTC, Juergen-J commented on phonebook-api/src/main/java/com/telran/phonebookapi/repository/ContactRepository.java
> +public interface ContactRepository extends JpaRepository<Contact, Integer> {
уберу

2021-09-06 20:17 UTC, Juergen-J commented on phonebook-api/build.gradle
завтра обсудим

2021-09-06 21:44 UTC, AR1988 requested changes

2021-09-06 21:44 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Group.java
> +    Family,
Upper case

2021-09-06 21:44 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/entity/ContactTest.java
> +
Проверить эти два импорта ошибок

2021-09-07 10:05 UTC, AR1988 approved these changes

2021-09-07 10:06 UTC, merged