PB-15 create repositories for entities
tel-ran-de/phonebook-16-19-2 pull request #8
Opened 2021-09-08 12:38 UTC by VolvachevaNatalya

2021-09-08 14:03 UTC, AR1988 requested changes

2021-09-08 14:03 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    private List<Phone> phones = new ArrayList<>(); // to avoid null pointer exception when creating entity via default constructor and adding new phone
Поддерживаю, удали пожалуйста комментарий

2021-09-08 14:03 UTC, AR1988 commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +//        emails = new ArrayList<>();
удали закомментированные строки

2021-09-08 14:03 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContactId = contactRepository.save(contact).getId();
var?

2021-09-08 14:03 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContact = contactRepository.findById(savedContactId).orElseThrow();
var?

2021-09-08 14:03 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContact = contactRepository.findById(savedContactId).orElseThrow();
var?

2021-09-08 14:03 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContactOptional = contactRepository.findById(savedContactId);
var?

2021-09-08 14:03 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +public class RepositoriesTest {
Перепиши пожалуйста тесты с использованием
```
    @Autowired
    TestEntityManager entityManager;
```
все сохранения выполняй с помощью entityManager
к примеру 

`
        Contact ivan= new Contact("Ivan", "Petrov");
        entityManager.persist(ivan);

        entityManager.flush();
        entityManager.clear();
        ...
`
так же необходимо создать в папке _phonebook-api/src/test_ создать новую директорию "resources"  внутри которой будет лежать файл конфигурации "application.properties" внутри него нужно указать необходимые настройки.
В данном случае только одну : spring.jpa.hibernate.ddl-auto=create-drop

так же в build.gradle нужно подключить зависимость для определения тестовой бд.
testImplementation 'com.h2database:h2'

2021-09-08 18:18 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +public class RepositoriesTest {
> так же необходимо создать в папке _phonebook-api/src/test_ создать новую директорию "resources" внутри которой будет лежать файл конфигурации "application.properties" внутри него нужно указать необходимые настройки.

просмотрел, это уже есть, сорри

2021-09-08 21:36 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +    private List<Phone> phones = new ArrayList<>(); // to avoid null pointer exception when creating entity via default constructor and adding new phone
Done

2021-09-08 21:37 UTC, VolvachevaNatalya commented on phonebook-api/src/main/java/com/telran/phonebookapi/entity/Contact.java
> +//        emails = new ArrayList<>();
Done

2021-09-08 21:37 UTC, VolvachevaNatalya commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +public class RepositoriesTest {
Done (not sure if it's done correctly but it works)

2021-09-08 21:39 UTC, VolvachevaNatalya commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContactOptional = contactRepository.findById(savedContactId);
https://www.geeksforgeeks.org/var-keyword-in-java/

2021-09-09 06:49 UTC, AR1988 requested changes

2021-09-09 06:49 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContactOptional = contactRepository.findById(savedContactId);
Замени все var на явное объявление типа

2021-09-09 06:49 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContactId = contactRepository.save(contact).getId();
var -> long

2021-09-09 06:49 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContact = contactRepository.findById(contactId).orElseThrow();
var -> Contact

2021-09-09 06:49 UTC, AR1988 commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var contactId = entityManager.persist(new Contact()).getId();
var -> long

2021-09-09 08:28 UTC, VolvachevaNatalya commented on phonebook-api/src/test/java/com/telran/phonebookapi/repository/RepositoriesTest.java
> +        var savedContactId = contactRepository.save(contact).getId();
Fixed

2021-09-09 09:30 UTC, AR1988 approved these changes, later dismissed

2021-09-09 10:15 UTC, AR1988 approved these changes

2021-09-09 10:15 UTC, merged